Fixed transparentDataEncryption property status to state
Azure/PSRule.Rules.Azure pull request #1505
Opened 2022-07-04 20:50 UTC by Dylan-Prins

## PR Summary

## PR Checklist

- [ ] PR has a meaningful title
- [ ] Summarized changes
- [ ] Change is not breaking
- [ ] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [ ] Unit tests created/ updated
  - [ ] Rule documentation created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2022-07-04 22:33 UTC, BernieWhite commented
@Dylan-Prins Thanks for the PR. Looks like there is a difference between various API versions or the provider documentation is wrong. The newer use `state` where the older is `status`. If we can verify that `status` was an error, happy to accept you change. Otherwise we should update it to accept either `status` or `state` as `Enabled`.

If the later, to get the tests to pass we need to add an entry for `database-C` that uses the `state` property here: https://github.com/Azure/PSRule.Rules.Azure/blob/ca694e0833548b49cf004f9e30abb156276c55dd/tests/PSRule.Rules.Azure.Tests/Resources.SQL.json#L436-L491

[2014-04-01](https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/2014-04-01/servers/databases/transparentdataencryption?tabs=bicep)

[latest](https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/servers/databases/transparentdataencryption?tabs=bicep)

@ms-sambell Did you notice something similar?

2022-07-05 07:23 UTC, Dylan-Prins commented
I see! I will add an if statement.
How can I check on API-Version in the if statement?

From: Bernie White ***@***.***>
Sent: Tuesday, July 5, 2022 12:33 AM
To: Azure/PSRule.Rules.Azure ***@***.***>
Cc: Dylan Prins ***@***.***>; Mention ***@***.***>
Subject: Re: [Azure/PSRule.Rules.Azure] Fixed transparentDataEncryption property status to state (PR #1505)


@Dylan-Prins<https://github.com/Dylan-Prins> Thanks for the PR. Looks like there is a difference between various API versions or the provider documentation is wrong. The newer use state where the older is status. If we can verify that status was an error, happy to accept you change. Otherwise we should update it to accept either status or state as Enabled.

If the later, to get the tests to pass we need to add an entry for database-C that uses the state property here: https://github.com/Azure/PSRule.Rules.Azure/blob/ca694e0833548b49cf004f9e30abb156276c55dd/tests/PSRule.Rules.Azure.Tests/Resources.SQL.json#L436-L491

2014-04-01<https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/2014-04-01/servers/databases/transparentdataencryption?tabs=bicep>

latest<https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/servers/databases/transparentdataencryption?tabs=bicep>

@ms-sambell<https://github.com/ms-sambell> Did you notice something similar?

—
Reply to this email directly, view it on GitHub<https://github.com/Azure/PSRule.Rules.Azure/pull/1505#issuecomment-1174437497>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACC7A6FRSCE747G5PB7PF3DVSNRCTANCNFSM52UFQV6A>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>


InSpark

2022-07-05 08:57 UTC, BernieWhite requested changes
@Dylan-Prins Nice work on the test resource. I think your suggestion is better to conditionally detect based on API version, but there is some specific cases around it.

Based on your suggestion, I am fine with removing `database-C` and just updating `database-B` with `state` as an exports from Azure will be using a newer API version the specific case we are testing should always be `state`.

2022-07-05 08:57 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1
> +        $Assert.HasFieldValue($config, 'Properties.state', 'Enabled');
The property `apiVersion` will not exist if exported with _in-flight_ scenarios, but latest API version should be used. We only need to catch the case when older IaC is used.

```suggestion
        if ($Assert.HasFieldValue($config, 'apiVersion', '2014-04-01').Result) {
            $Assert.HasFieldValue($config, 'Properties.status', 'Enabled');
        }
        else {
            $Assert.HasFieldValue($config, 'Properties.state', 'Enabled');
        }
```

2022-07-05 10:25 UTC, BernieWhite approved these changes
@Dylan-Prins Great, all good to go. I'll update the branch for main and merge. Thanks!

2022-07-05 10:59 UTC, merged