1478/check custom script extension usage
Azure/PSRule.Rules.Azure pull request #1684
Opened 2022-09-20 23:33 UTC by ms-sambell

## PR Summary

Creating a VM and VMSS rule for checking the custom script extension usage for `secureString` functions that aren't the protectedSettings area.

## PR Checklist

- [ ] PR has a meaningful title
- [ ] Summarized changes
- [ ] Change is not breaking
- [ ] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [ ] Unit tests created/ updated
  - [ ] Rule documentation created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2022-09-21 01:54 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1
> +        $vmConfig = @(GetSubResources -ResourceType 'extensions' );
Try both `extenstions` and `Microsoft.Compute/virtualMachines/extensions` since both are valid.

2022-09-21 01:57 UTC, BernieWhite commented on tests/PSRule.Rules.Azure.Tests/Resources.VMSS.json
> +                                    "commandToExecute": "[concat('Write-Output ', secureString('adminPassword'))]"
Is `secureString` a function?

2022-09-21 12:00 UTC, ms-sambell commented
Halting work on this until this bug is fixed: https://github.com/Azure/PSRule.Rules.Azure/issues/1687

2022-10-18 14:00 UTC, BernieWhite requested changes
@ms-sambell Nice. Double check the comments below.

2022-10-18 14:00 UTC, BernieWhite commented on docs/en/rules/Azure.VM.ScriptExtensions.md
> +ARM
Maybe something like:

```suggestion
To deploy VM extensions that pass this rule:

- Set any secure values within `properties.protectedSettings`.
```

2022-10-18 14:00 UTC, BernieWhite commented on docs/en/rules/Azure.VM.ScriptExtensions.md
> +
```suggestion

To deploy VM extensions that pass this rule:

- Set any secure values within `properties.protectedSettings`.

```

2022-10-18 14:00 UTC, BernieWhite commented on docs/en/rules/Azure.VMSS.ScriptExtensions.md
> +Recommendation
Probably need to set something here similar to VM.

2022-10-18 14:00 UTC, BernieWhite commented on docs/en/rules/Azure.VM.ScriptExtensions.md
> +Move the script in the `properties.settings` property to the `properties.protectedSettings` property.
```suggestion
Consider specifying secure values within `protectedSettings` to avoid exposing secrets during extension deployments.
```

2022-10-18 14:00 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1
> +Rule 'Azure.VM.ScriptExtensions' -Ref 'AZR-000290' -Type 'Microsoft.Compute/virtualMachines', 'Microsoft.Computer/virtualMachines/CustomScriptExtension', 'Microsoft.Compute/virtualMachines/extensions
Will need to bump the `ref` and `ruleSet`.

2022-10-18 14:00 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.VMSS.Rule.ps1
> +Rule 'Azure.VMSS.ScriptExtensions' -Ref 'AZR-000291' -Type 'Microsoft.Compute/virtualMachineScaleSets', 'Microsoft.Computer/virtualMachineScaleSets/CustomScriptExtension', 'Microsoft.Compute/virtualM
Will need to bump the `ref` and `ruleSet`.

2022-10-22 06:35 UTC, ms-sambell commented
I've addressed the PR feedback and cleaned up the PR. I'm still not sure how to leverage the SecretReference that exists in the Export-Template file during the rule evaluation. 

Once this is clear I should be able to complete this. I've pinged you on the other issue (Deployment scopes) for clarification.

2022-11-16 12:11 UTC, BernieWhite approved these changes
@ms-sambell Nice work! I have a few comments below, but otherwise all good to merge.

2022-11-16 12:19 UTC, ms-sambell commented on src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1
> +        $vmConfig = @(GetSubResources -ResourceType 'extensions', 'Microsoft.Compute/virtualMachines/extensions' );
I missed that. Good call out. 

I believe your code suggestion handles that (thank you).

2022-11-16 16:21 UTC, merged