Added Azure.AppConfig.GeoReplication
Azure/PSRule.Rules.Azure pull request #1735
Opened 2022-09-30 16:49 UTC by bengeset96

## PR Summary

Fixes #1688

Added Azure.AppConfig.GeoReplication rule. 

This rule is aimed at app configuration stores, ensuring that they have one or more replicas providing better resiliency to region outages.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2022-09-30 17:46 UTC, bengeset96 commented
@BernieWhite 

Should be ready for review.

2022-10-01 06:01 UTC, BernieWhite requested changes
@bengeset96 Great work. Just a few minor tweaks to make this even better. If you have any questions please let me know.

2022-10-01 11:12 UTC, bengeset96 commented on src/PSRule.Rules.Azure/rules/Azure.AppConfig.Rule.ps1
> +            if ($appConfigLocation -ne $replicaLocation) { $Assert.Pass() } else { $Assert.Fail($LocalizedData.ReplicaInSecondaryNotFound) }
I agree. This was not optimal from my side and I will adjust accordingly.

2022-10-01 11:26 UTC, bengeset96 commented
@BernieWhite 

I have refactored the rule now. Do you mind to take a look on it?

`2022_09` baseline included, please inform if should be adjusted to `2022_12`.

2022-10-02 03:35 UTC, BernieWhite requested changes
@bengeset96 One minor tweak. Otherwise all good. We're fine to go with `2022_09` for this rule. I'll merge lock in the baseline after we merge this rule.

2022-10-02 03:35 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.AppConfig.Rule.ps1
> +    $Assert.Greater($replicas, '.', 0).Reason($LocalizedData.ReplicaInSecondaryNotFound)
```suggestion
    $Assert.Greater($replicas, '.', 0).Reason($LocalizedData.ReplicaInSecondaryNotFound).PathPrefix('resources')
```

2022-10-02 06:33 UTC, bengeset96 commented
Done :)

2022-10-02 10:28 UTC, BernieWhite approved these changes
Thanks @bengeset96 great work. All good to merge.

2022-10-02 10:28 UTC, merged