Added Azure.MySQL.UseFlexible
Azure/PSRule.Rules.Azure pull request #1844
Opened 2022-11-11 21:09 UTC by bengeset96

## PR Summary

Fixes #1841 

Added Azure.MySQL.UseFlexible rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2022-11-11 21:16 UTC, bengeset96 commented
@BernieWhite 

I want to merge main into this branch after we have the new updates to the `GeoRedundantBackup` rule as it has some dependencies.

The idea here is:

- We include flexible deployment model so the customer see that he passed the rule.
- Run the rule with `-Level Warning` so it does not produce terminating error because I can't really see that the single server deployment model has been given any last date. Maybe change it to default behaviour when we see that there is an date settled for the fully retirement.

2022-11-14 14:08 UTC, BernieWhite requested changes
Thanks @bengeset96. There are a few differences so I agree we shouldn't make that break pipelines yet and a warning is the best approach.

I've added a few comments to suggest alternatives for wording but let me know if you have an questions.

2022-11-14 14:08 UTC, BernieWhite commented on docs/en/rules/Azure.MySQL.UseFlexible.md
> +Azure Database for MySQL Flexible Server to bring you the best of Azure’s open-source database platform.
```suggestion
Azure Database for MySQL Flexible Server provides additional options for resilience and scalability above the Single Server deployment model.
```

2022-11-14 14:11 UTC, bengeset96 commented on docs/en/rules/Azure.MySQL.UseFlexible.md
> +Check out the `NOTES` section for more details about the retirement path and migration steps.
Yes, this is just my mistake.

2022-11-14 14:42 UTC, bengeset96 commented on src/PSRule.Rules.Azure/rules/Azure.MySQL.Rule.ps1
> +    }
@BernieWhite 

Great, I'll start to to use this approach more!

2022-11-15 14:21 UTC, BernieWhite approved these changes
Great work @bengeset96 ! All good to merge.

2022-11-15 14:21 UTC, merged