Added Azure.MariaDB.GeoRedundantBackup
Azure/PSRule.Rules.Azure pull request #1849
Opened 2022-11-13 16:36 UTC by bengeset96

## PR Summary

Fixes #1848

Added Added Azure.MariaDB.GeoRedundantBackup rule.

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2022-11-14 14:47 UTC, BernieWhite requested changes
@bengeset96 Looks great. Just one correction.

2022-11-14 14:47 UTC, BernieWhite commented on docs/en/rules/Azure.MariaDB.GeoRedundantBackup.md
> +- [Backup and restore in Azure Database for MariaDB](https://learn.microsoft.com/azure/templates/microsoft.dbformariadb/servers)
```suggestion
- [Backup and restore in Azure Database for MariaDB](https://learn.microsoft.com/azure/mariadb/concepts-backup)
```

2022-11-15 09:00 UTC, bengeset96 commented
@BernieWhite 

Adjusted 😃

2022-11-15 13:52 UTC, BernieWhite approved these changes
Thanks @bengeset96. All good to merge.

2022-11-15 13:52 UTC, merged