Added Azure.APIM.MultiRegionGateway
Azure/PSRule.Rules.Azure pull request #1911
Opened 2022-11-27 13:52 UTC by BenjaminEngeset

## PR Summary

Fixes #1910 

Added Azure.APIM.MultiRegionGateway rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2022-11-27 14:15 UTC, BenjaminEngeset commented
@BernieWhite 

Hey Bernie, do you mind taking a look on this when you have the chance?

2022-11-28 12:32 UTC, BernieWhite requested changes
Thanks @BenjaminEngeset looks good. I have a few suggestions. Let me know what you think or if you have any questions.

2022-11-28 12:32 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1
> +    $Assert.Less($gateways, '.', 1).Reason($LocalizedData.APIMMultiRegionGateway)
I think we can simplify this to:

```suggestion
    $gateways = $PSRule.GetPath($TargetObject, 'properties.additionalLocations');
    foreach ($gateway in $gateways) {
        $Assert.HasDefaultValue($gateway, 'disableGateway', $False);
    }
```

2022-11-28 12:32 UTC, BernieWhite commented on docs/en/rules/Azure.APIM.MultiRegionGateway.md
> +Enable multi-region deployment gateways.
```suggestion
Consider enabling each regional API gateway location for multi-region redundancy.
```

2022-11-28 12:32 UTC, BernieWhite commented on docs/en/rules/Azure.APIM.MultiRegionGateway.md
> +Azure API Management supports multi-region deployment. If the *primary* region goes offline, the secondary regions continue to serve API requests using the most recent gateway configuration. If a *re
@BenjaminEngeset Each API gateway location is active-active, maybe lets change the working slightly to something like the following unless you have some alternative suggestions.

```suggestion
Azure API Management supports multi-region deployment.
Deploy API Management in multiple locations to:

- Provide active-active redundancy for API gateway requests across Azure regions.
- Serve the request from the closest API gateway region to the original request.

API gateways can be disabled to enabled you to test failover of your API workloads to another region.
When disabled, an API gateway will not route API traffic.
You should reenable API gateways after you have concluded failover testing to ensure that the API gateway is available for failover if another region becomes unavailable.

If a region goes offline, API requests are automatically routed around the failed region to the next closest gateway.
```

2022-11-28 13:41 UTC, BenjaminEngeset commented
Great feedback, great to also learn from pull requests! I liked all the suggestions and I've implemented them.

Just a quick one before merge, does `GetPath` helper method return the property value such as the whole `additionalLocations` array or does it traverse thru the array and enumerate all the objectts one by one and return those?

2022-11-30 07:31 UTC, BernieWhite approved these changes
@BenjaminEngeset no worries. Great thanks for that. All good to merge.

2022-11-30 11:42 UTC, merged