Added Azure.VM.AMA
Azure/PSRule.Rules.Azure pull request #1927
Opened 2022-12-04 21:22 UTC by BenjaminEngeset

## PR Summary

Added Azure.VM.AMA rule.

## PR Checklist

- [x] PR has a meaningful title
- [ ] Summarized changes
- [ ] Change is not breaking
- [ ] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [ ] Unit tests created/ updated
  - [ ] Rule documentation created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2022-12-04 21:42 UTC, BenjaminEngeset commented
@BernieWhite 

Could you brainstorm on this one with me. 

It all started with #1868 

Currently there is no proper way of configuring this programmatically. The only real option seems to be [Auto-deploy Azure Monitor Agent](https://learn.microsoft.com/en-us/azure/defender-for-cloud/auto-deploy-azure-monitoring-agent). I've requested the docs team to update accordingly. I feel it's a bad idea to point customers to manually configure each virtual machine from the portal. With this option also `Azure Security Agent (ASA) extension` is installed which is needed for Defender for Cloud and specific data collection rules and assignments. These collection rules are not available programmatically, only the basic ones.

Hence, the change in the rule. The rule instead focus towards customers installing the agent for general usage for collecting monitoring data.

It will then be supported by additional rules like `Azure.VM.AMADataCollectionRule/Azure.VM.AMADCR` and `Azure.VM.AMADataCollectionRuleAssignment/Azure.VM.AMADCRAssignment` that checks for that at least one rule is configured and that at lest one assignment is configured.

When documentation and steps are available programatically for the Defender for Cloud part, we introduce an additionally rule like `Azure.AMADefender` that checks for that the agent is installed, ASA extension is installed, correct data collection rules and assignments are configured.

2022-12-05 13:13 UTC, BernieWhite commented
> 

@BenjaminEngeset Having a look at this the AMA is deployed via Azure Policy via an assignment _Default Defender for Cloud provisioning Azure Monitor agent_. My guess is there won't will be an auto provisioning configuration similar to previous Log Analytics Agent configuration because Microsoft Defender for Cloud is mostly already configured via policy and `Microsoft.Security/autoProvisioningSettings` was more an artifact of before policy was the primary mechanism to configure MDfC.

So making the rule aligned to OpEx is a good approach. Not entirely sure on the DCR rules, but let's have a look at those in a separate PR. Either way it's still a good rule to have.

2022-12-05 13:22 UTC, BernieWhite requested changes
@BenjaminEngeset Looks great. One minor change.

2022-12-05 13:22 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1
> +Rule 'Azure.VM.AMA' -Ref 'AZR-000344' -Type 'Microsoft.Compute/virtualMachines' -Tag @{ release = 'Preview'; ruleSet = '2022_12'; } {
In the context of general monitoring AMA is generally available so we don't need to mark it as preview.

```suggestion
Rule 'Azure.VM.AMA' -Ref 'AZR-000344' -Type 'Microsoft.Compute/virtualMachines' -Tag @{ release = 'GA'; ruleSet = '2022_12'; } {
```

2022-12-06 18:35 UTC, BenjaminEngeset commented
> > 
> 
> @BenjaminEngeset Having a look at this the AMA is deployed via Azure Policy via an assignment _Default Defender for Cloud provisioning Azure Monitor agent_. My guess is there won't will be an auto provisioning configuration similar to previous Log Analytics Agent configuration because Microsoft Defender for Cloud is mostly already configured via policy and `Microsoft.Security/autoProvisioningSettings` was more an artifact of before policy was the primary mechanism to configure MDfC.
> 
> So making the rule aligned to OpEx is a good approach. Not entirely sure on the DCR rules, but let's have a look at those in a separate PR. Either way it's still a good rule to have.

Thanks for the great feedback @BernieWhite and information.

2022-12-06 19:09 UTC, BenjaminEngeset commented
@BernieWhite 

Ready for review.

2022-12-07 00:13 UTC, BernieWhite approved these changes
Great work @BenjaminEngeset. All good to merge.

2022-12-07 08:17 UTC, merged