Added Azure.ContainerApp.Name
Azure/PSRule.Rules.Azure pull request #2095
Opened 2023-03-18 18:33 UTC by BenjaminEngeset

## PR Summary

Fixes #2094 

Added Azure.ContainerApp.Name rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2023-03-19 04:17 UTC, BernieWhite requested changes
Nice work @BenjaminEngeset. Just a few points to tweak this further. Let me know if you have any questions.

2023-03-19 04:17 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.ContainerApp.Rule.yaml
> +        match: '^([a-z][0-9a-z-]{1,30}[0-9]|[a-z][0-9])$'
Maybe try this expression instead.

```suggestion
        match: '^([a-z][0-9a-z-]{0,30}[0-9a-z])$'
```

2023-03-21 11:53 UTC, BenjaminEngeset commented
@BernieWhite looks like it didn't work, but looks like you are aware of it.

2023-03-21 16:56 UTC, BernieWhite requested changes
I added an issue for future support for `caseSensitive` of `match`.

The rule test is failed for another reason, see below.

2023-03-21 16:56 UTC, BernieWhite commented on tests/PSRule.Rules.Azure.Tests/Azure.ContainerApp.Tests.ps1
> +            ResourceType = 'Microsoft.Resources/deployments'
Needs to be the same type as the rule.

```suggestion
            ResourceType = 'Microsoft.App/containerApps'
```

2023-03-21 17:00 UTC, BenjaminEngeset commented
> I added an issue for future support for `caseSensitive` of `match`.
> 
> The rule test is failed for another reason, see below.

Great! Fixed btw.

2023-03-21 17:09 UTC, BernieWhite approved these changes
Thanks @BenjaminEngeset looks good to me. Should be good to merge.

2023-03-22 04:54 UTC, BernieWhite requested changes
See suggestions below.

2023-03-22 04:56 UTC, BernieWhite commented
Adding that in.

2023-03-23 07:49 UTC, BernieWhite approved these changes
Thanks @BenjaminEngeset. All good to merge.

2023-03-23 07:49 UTC, merged