Added Azure.SQLMI.AADOnly
Azure/PSRule.Rules.Azure pull request #2127
Opened 2023-04-01 08:15 UTC by BenjaminEngeset

## PR Summary

Fixes #2118 

Added Azure.SQLMI.AADOnly rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2023-04-01 08:16 UTC, BenjaminEngeset commented
@BernieWhite Let me know.

2023-04-03 16:13 UTC, BernieWhite requested changes
Great work @BenjaminEngeset! Just a few suggested updates. If you have any questions please let me know.

2023-04-03 16:13 UTC, BernieWhite commented on docs/en/rules/Azure.SQLMI.AADOnly.md
> +SQL Managed Instance should be using Azure AD authentication. SQL legacy authentication mechanisms such as SQL logins are unable to provide sufficient protection for identities. Azure AD authenticati
```suggestion
Azure SQL Managed Instance supports authentication with SQL logins and Azure AD authentication.

By default, authentication with SQL logins is enabled.
SQL logins are unable to provide sufficient protection for identities.
Azure AD authentication provides strong protection controls including conditional access, identity governance, and privileged identity management.

Once you decide to use Azure AD authentication, you can disable authentication with SQL logins.
```

2023-04-03 20:55 UTC, BenjaminEngeset commented
@BernieWhite I think we are all set, check the latest updates.

2023-04-04 08:55 UTC, merged