Updated Azure.APIM.EncryptValues
Azure/PSRule.Rules.Azure pull request #2147
Opened 2023-04-09 10:25 UTC by BenjaminEngeset

## PR Summary

Updated Azure.APIM.EncryptValues rule.

Breaking change, unsure if baseline should be updated.

Fixes #2146

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [ ] Change is not breaking
- [ ] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - x ] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2023-04-09 10:28 UTC, BenjaminEngeset commented
@BernieWhite Let me know :)

2023-04-14 17:07 UTC, BernieWhite requested changes
@BenjaminEngeset looks great. Just a few minor tweak and it should be good to go. When you update the `ruleSet` it will reduce the number of older baselines so you will need to subtract one from each of these numbers in the tests for this to pass.

2023-04-14 17:07 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1
> +        [switch]$GlobalPolicy
```suggestion
        [string]$Node
```

2023-04-15 07:32 UTC, BenjaminEngeset commented
> @BenjaminEngeset looks great. Just a few minor tweak and it should be good to go. When you update the `ruleSet` it will reduce the number of older baselines so you will need to subtract one from each of these numbers in the tests for this to pass.

Hey Bernie, do you mind giving me the instruction for this? I'm unsure where this should be changed. Thanks.

2023-04-17 13:03 UTC, BernieWhite reviewed
Hi @BenjaminEngeset I'm made the updates to the tests and a few changes to the docs.

Please review and let me know if you are happy with the updates from your perspective, or if you want to make any further changes. Otherwise we should be good to merge.

2023-04-17 13:05 UTC, BenjaminEngeset commented
> Hi @BenjaminEngeset I'm made the updates to the tests and a few changes to the docs.
> 
> Please review and let me know if you are happy with the updates from your perspective, or if you want to make any further changes. Otherwise we should be good to merge.

@BernieWhite Was just checking, I am very happy and great updates making it even better. Lets merge.

2023-04-19 00:18 UTC, BernieWhite approved these changes
Thanks @BenjaminEngeset. All good to merge.

2023-04-19 00:18 UTC, merged