Added Azure.Arc.Kubernetes.Defender
Azure/PSRule.Rules.Azure pull request #2182
Opened 2023-05-03 19:37 UTC by BenjaminEngeset

## PR Summary

Fixes #2124 

Added Azure.Arc.Kubernetes.Defender rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2023-05-03 19:38 UTC, BenjaminEngeset commented
@BernieWhite Let me know what you think about this one.

2023-05-05 13:51 UTC, BernieWhite requested changes
Great work @BenjaminEngeset. A few suggestions otherwise all good.

2023-05-05 13:51 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.Arc.Rule.ps1
> +Rule 'Azure.Arc.Kubernetes.Defender' -Ref 'AZR-000373' -Type 'Microsoft.Kubernetes/connectedClusters' -Tag @{ release = 'Preview'; ruleSet = '2023_06'; } {
Let's add a label for LT-1.

```suggestion
Rule 'Azure.Arc.Kubernetes.Defender' -Ref 'AZR-000373' -Type 'Microsoft.Kubernetes/connectedClusters' -Tag @{ release = 'Preview'; ruleSet = '2023_06'; 'Azure.WAF/pillar' = 'Security'; } -Labels @{ 'Azure.MCSB.v1/control' = 'LT-1' } {
```

2023-05-05 13:51 UTC, BernieWhite commented on docs/en/rules/Azure.Arc.Kubernetes.Defender.md
> +- [Azure deployment reference](https://learn.microsoft.com/azure/templates/microsoft.kubernetesconfiguration/extensions)
Let's add a reference to LT-1.

```suggestion
- [LT-1: Enable threat detection capabilities](https://learn.microsoft.com/security/benchmark/azure/baselines/azure-arc-enabled-kubernetes-security-baseline#lt-1-enable-threat-detection-capabilities)
- [Azure deployment reference](https://learn.microsoft.com/azure/templates/microsoft.kubernetesconfiguration/extensions)
```

2023-05-05 14:27 UTC, BenjaminEngeset commented
@BernieWhite Great to hear and thanks for the suggestions. Adjusted.

2023-05-05 15:26 UTC, BernieWhite approved these changes
Thanks @BenjaminEngeset. All good to merge.

2023-05-05 15:26 UTC, merged