Added Azure.Arc.Server.MaintenanceConfig
Azure/PSRule.Rules.Azure pull request #2183
Opened 2023-05-05 14:22 UTC by BenjaminEngeset

## PR Summary

Fixes #2122 

Added Azure.Arc.Server.MaintenanceConfig rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2023-05-05 14:22 UTC, BenjaminEngeset commented
@BernieWhite Lemme know what you're thinking.

2023-05-07 12:37 UTC, BernieWhite requested changes
Nice work @BenjaminEngeset. I've added a few suggestions.

Let me know if you have any questions.

2023-05-07 12:37 UTC, BernieWhite commented on docs/en/rules/Azure.Arc.Server.MaintenanceConfig.md
> +Consider associating a maintenance configuration for Arc-enabled servers.
```suggestion
Consider automatically managing and applying operating system updates with a maintenance configuration.
```

2023-05-07 13:06 UTC, BenjaminEngeset commented
@BernieWhite Thanks for the great feedback. I've adjusted accordingly now :)

2023-05-10 07:05 UTC, BernieWhite approved these changes
Thanks @BenjaminEngeset. All good to merge.

2023-05-10 07:05 UTC, merged