Added Azure.AppGw.MigrateV2
Azure/PSRule.Rules.Azure pull request #2193
Opened 2023-05-08 19:47 UTC by BenjaminEngeset

## PR Summary

Fixes #2185

Added Azure.AppGw.MigrateV2 rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2023-05-08 19:49 UTC, BenjaminEngeset commented
@BernieWhite Let me know your thoughts if this is carried out the right way.

2023-05-10 13:26 UTC, BernieWhite requested changes
Great work @BenjaminEngeset. I've added a few suggestion. Please let me know if you have any questions.

2023-05-10 13:26 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.AppGw.Rule.yaml
> +      - WAF_v2
Check for by `name` or `tier` depending which is defined.

```suggestion
    anyOf:
    - field: properties.sku.tier
      in:
        - Standard_v2
        - WAF_v2
    - field: properties.sku.name
      in:
        - Standard_v2
        - WAF_v2
```

2023-05-10 13:26 UTC, BernieWhite commented on docs/en/rules/Azure.AppGw.MigrateV2.md
> +Migrate Application Gateways from a v1 SKU to a v2 SKU.
```suggestion
Migrate deprecated v1 Application Gateways to a v2 SKU before retirement to avoid service disruption.
```

2023-05-10 20:11 UTC, BenjaminEngeset commented
@BernieWhite All made sense, thanks for the great feedback. Check latest updates from me.

2023-05-11 19:19 UTC, BernieWhite approved these changes
Thanks for the updates @BenjaminEngeset. All good to merge.

2023-05-11 19:20 UTC, merged