Added Azure.Defender.CosmosDb
Azure/PSRule.Rules.Azure pull request #2210
Opened 2023-05-13 08:42 UTC by BenjaminEngeset

## PR Summary

Fixes #2204
Fixes a topic within #1632 

Added Azure.Defender.CosmosDb rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2023-05-13 08:44 UTC, BenjaminEngeset commented
@BernieWhite Let me know :)

2023-05-16 14:26 UTC, BernieWhite requested changes
Thanks @BenjaminEngeset. Great work!

I've added a few suggestions, otherwise all good to merge.

2023-05-16 14:26 UTC, BernieWhite commented on docs/en/rules/Azure.Defender.CosmosDb.md
> +Microsoft Defender for Azure Cosmos DB provides additional security for Azure Cosmos DB accounts.
```suggestion
Microsoft Defender for Azure Cosmos DB provides additional security insight for Azure Cosmos DB accounts.
```

2023-05-16 14:26 UTC, BernieWhite commented on docs/en/rules/Azure.Defender.CosmosDb.md
> +Consider using Microsoft Defender for Azure Cosmos DB to provide additional security for Azure Cosmos DB accounts.
```suggestion
Consider using Microsoft Defender for Azure Cosmos DB to provide additional security insights for Azure Cosmos DB accounts.
```

2023-05-16 14:26 UTC, BernieWhite commented on docs/en/rules/Azure.Defender.CosmosDb.md
> +Microsoft Defender for Azure Cosmos DB is currently available only for the API for NoSQL.
```suggestion
Microsoft Defender for Azure Cosmos DB is currently available only for the NoSQL API.
```

2023-05-16 14:26 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.Defender.Rule.yaml
> +    Azure.MCSB.v1/control: LT-1
```suggestion
    Azure.MCSB.v1/control: [ 'DP-2', 'LT-1' ]
```

2023-05-16 14:26 UTC, BernieWhite commented on docs/en/rules/Azure.Defender.CosmosDb.md
> +- [LT-1: Enable threat detection capabilities](https://learn.microsoft.com/security/benchmark/azure/baselines/azure-cosmos-db-security-baseline#lt-1-enable-threat-detection-capabilities)
```suggestion
- [DP-2: Monitor anomalies and threats targeting sensitive data](https://learn.microsoft.com/security/benchmark/azure/baselines/azure-cosmos-db-security-baseline#dp-2-monitor-anomalies-and-threats-targeting-sensitive-data)
- [LT-1: Enable threat detection capabilities](https://learn.microsoft.com/security/benchmark/azure/baselines/azure-cosmos-db-security-baseline#lt-1-enable-threat-detection-capabilities)
```

2023-05-16 14:26 UTC, BernieWhite requested changes
Thanks @BenjaminEngeset. Great work!

I've added a few suggestions, otherwise all good to merge.

2023-05-16 15:53 UTC, BenjaminEngeset commented
@BernieWhite Great and thanks for the feedback. I have updated the rule now.

2023-05-16 17:34 UTC, BernieWhite approved these changes
Thanks @BenjaminEngeset. All good to merge.

2023-05-16 22:53 UTC, merged