Added Azure.Cosmos.DefenderCloud
Azure/PSRule.Rules.Azure pull request #2218
Opened 2023-05-16 17:48 UTC by BenjaminEngeset

## PR Summary

Fixes #2203

Added Azure.Cosmos.DefenderCloud rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2023-05-16 17:53 UTC, BenjaminEngeset commented
@BernieWhite Let me know what you're thinking. I noticed a unknown property called `EnabledApiTypes`. Is this something you are aware of? I cannot find it, neither in a prior API version.

Since we have this in our template, the pre-condition does not work as it should. Should we build in additional logic for this?

https://github.com/Azure/PSRule.Rules.Azure/blob/478982edcf94df1c138a386cb9ae505e147bc89d/tests/PSRule.Rules.Azure.Tests/Resources.Cosmos.json#L27

2023-05-19 13:38 UTC, BernieWhite commented
> @BernieWhite Let me know what you're thinking. I noticed an unknown property called `EnabledApiTypes`. Is this something you are aware of? I cannot find it, neither in a prior API version.
> 
> Since we have this in our template, the pre-condition does not work as it should. Should we build in additional logic for this?
> 
> https://github.com/Azure/PSRule.Rules.Azure/blob/478982edcf94df1c138a386cb9ae505e147bc89d/tests/PSRule.Rules.Azure.Tests/Resources.Cosmos.json#L27

I think this is a runtime property. We shouldn't build any logic around it. We should use capabilities to determine what API is used.

2023-05-19 13:45 UTC, BenjaminEngeset commented
> > @BernieWhite Let me know what you're thinking. I noticed an unknown property called `EnabledApiTypes`. Is this something you are aware of? I cannot find it, neither in a prior API version.
> > Since we have this in our template, the pre-condition does not work as it should. Should we build in additional logic for this?
> > https://github.com/Azure/PSRule.Rules.Azure/blob/478982edcf94df1c138a386cb9ae505e147bc89d/tests/PSRule.Rules.Azure.Tests/Resources.Cosmos.json#L27
> 
> I think this is a runtime property. We shouldn't build any logic around it. We should use capabilities to determine what API is used.

@BernieWhite Great, agreed, then the rule is ready for review.

2023-05-19 15:19 UTC, BenjaminEngeset commented
@BernieWhite Updated the tests now.

2023-05-20 07:51 UTC, BernieWhite requested changes
Great work on the rule @BenjaminEngeset.

I'm thinking this should be opt-in by configuration because for the recommended case it is not required, and there is no additional settings that needs to be set.

Let's add a `AZURE_COSMOS_DEFENDER_PER_ACCOUNT` configuration value.

When set to `true` this rule would be evaluated, otherwise skipped.

2023-05-20 08:14 UTC, BenjaminEngeset commented
> Great work on the rule @BenjaminEngeset.
> 
> I'm thinking this should be opt-in by configuration because for the recommended case it is not required, and there is no additional settings that needs to be set.
> 
> Let's add a `AZURE_COSMOS_DEFENDER_PER_ACCOUNT` configuration value.
> 
> When set to `true` this rule would be evaluated, otherwise skipped.

Agreed, that makes the most sense. I'll adjust and ping you after.

2023-05-20 10:18 UTC, BenjaminEngeset commented
@BernieWhite I've updated it now and added test case for enablement. Let me know

2023-05-21 05:49 UTC, BernieWhite approved these changes
Thanks for the updates @BenjaminEngeset. Looks great. All good to merge.

2023-05-21 05:49 UTC, merged