Added Azure.Defender.Storage.SensitiveData
Azure/PSRule.Rules.Azure pull request #2233
Opened 2023-05-22 16:44 UTC by BenjaminEngeset

## PR Summary

Part of #2207 

Added Azure.Defender.Storage.SensitiveData rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2023-05-22 16:45 UTC, BenjaminEngeset commented
Hi @BernieWhite! What do you think?

2023-05-23 14:44 UTC, BernieWhite requested changes
Thanks @BenjaminEngeset. Minor suggestion on the docs, otherwise should be ok.

2023-05-23 14:44 UTC, BernieWhite commented on docs/en/rules/Azure.Defender.Storage.SensitiveData.md
> +Sensitive data threat detection in Microsoft Defender for Storage can be enabled at the subscription level and by doing so ensures all storage accounts in the subscription will be protected, includin
When don't need to include everything from the docs, just enough to understand what the feature is and why they should enable it.

```suggestion
Sensitive data threat detection is an additional security feature for Microsoft Defender for Storage.
When enabled Defender for Storage provides alerts when sensitive data is discovered.

The sensitive data threat detection capability helps teams:

- Identity where sensitive data is stored.
- Detect possible security incidents resulting is data exposure.

When enabling sensitive data threat detection, the sensitive data categories include built-in sensitive information types (SITs) in the default list of Microsoft Purview. 
It is possible to customize the Data Sensitivity Discovery for a organization, by creating custom sensitive information types (SITs).

Sensitive data threat detection in Microsoft Defender for Storage can be enabled at the subscription level and by doing so ensures all storage accounts in the subscription will be protected, including future ones.
```

2023-05-23 15:15 UTC, BenjaminEngeset commented
@BernieWhite Agreed, thanks for identifying and correcting. I have updated it now.

2023-05-25 04:27 UTC, BernieWhite approved these changes
Thanks @BenjaminEngeset. All good to merge.

2023-05-26 14:25 UTC, merged