Added Azure.Storage.DefenderCloud.SensitiveData
Azure/PSRule.Rules.Azure pull request #2236
Opened 2023-05-23 09:11 UTC by BenjaminEngeset

## PR Summary

Part of #2207 

Added Azure.Storage.DefenderCloud.SensitiveData rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2023-05-23 09:14 UTC, BenjaminEngeset commented
@BernieWhite When you have the time.

2023-05-28 15:27 UTC, BernieWhite requested changes
Great work @BenjaminEngeset. I have added a few suggestion for the documentation.

2023-05-28 15:27 UTC, BernieWhite commented on docs/en/rules/Azure.Storage.DefenderCloud.SensitiveData.md
> +- Override subscription level settings to configure specific storage accounts with custom sensitive data threat detection settings that differ from the settings configured at the subscription level.
```suggestion
When enabling sensitive data threat detection, the sensitive data categories include built-in sensitive information types (SITs) in the default list of Microsoft Purview.
It is possible to customize the Data Sensitivity Discovery for a organization, by creating custom sensitive information types (SITs).

Sensitive data threat detection in Microsoft Defender for Storage can be enabled at the subscription level and by doing so ensures all storage accounts in the subscription will be protected, including future ones.

When overriding sensitive data threat detection on individual Storage Account it is possible to configure custom sensitive data threat detection settings that differ from the settings configured at the subscription level.
```

2023-05-28 15:37 UTC, BenjaminEngeset commented
@BernieWhite Thanks for the great suggestions, they have been implemented. We had an overlapping rule reference, so I had to change it to `000391`.

2023-05-28 23:05 UTC, BernieWhite approved these changes
Great work @BenjaminEngeset. All good to merge.

2023-05-28 23:06 UTC, merged