Added Azure.KeyVault.RBAC
Azure/PSRule.Rules.Azure pull request #2243
Opened 2023-05-25 20:56 UTC by BenjaminEngeset

## PR Summary

Fixes #1916 

Added Azure.KeyVault.RBAC rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2023-05-25 21:11 UTC, BenjaminEngeset commented
@BernieWhite Let me know.

2023-05-26 15:59 UTC, BernieWhite requested changes
Great work @BenjaminEngeset. Just a few minor changes suggested. See below.

2023-05-26 15:59 UTC, BernieWhite commented on docs/en/rules/Azure.KeyVault.RBAC.md
> +pillar: Security
```suggestion
pillar: Security
```

2023-05-26 15:59 UTC, BernieWhite commented on docs/en/rules/Azure.KeyVault.RBAC.md
> +The Azure RBAC permission model has disadvantages when compared to access policies, that might effect e.g infrastructure as code deployments. There are scenarios where Azure RBAC might not be suitabl
```suggestion
The RBAC permission model may not be suitable for all use cases.
If this rule is not suitable for your use case, you can exclude or suppress the rule.
For information about limitations see _Azure role-based access control vs. access policies_ in the `LINKS` section.
```

2023-05-27 03:03 UTC, BernieWhite approved these changes
Great work @BenjaminEngeset. All good to merge.

2023-05-28 15:08 UTC, merged