Added Azure.ContainerApp.APIVersion
Azure/PSRule.Rules.Azure pull request #2399
Opened 2023-08-22 17:15 UTC by BenjaminEngeset

## PR Summary

Fixes #2398

Added Azure.ContainerApp.MigrateAPIVersion rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2023-08-22 17:16 UTC, BenjaminEngeset commented
Hi @BernieWhite. Let me know what you're thinking. Rule number 400 btw 🥳

2023-08-23 07:08 UTC, BernieWhite requested changes
Thanks @BenjaminEngeset. Great work.

I have made the following updates:

- I renamed the rule to short it to 35 characters.
- Updated `RuleDataExportVisitor` to allow the `apiVersion` property to be exposed from IaC.

Let's remove `apiVersion` from one of the resource (i've provided a suggestion on this) so that we test for the case when no `apiVersion` is set, which should pass. This will be the case we need to handle for _in-flight_.

Double check the changes and let me know if you are fine with these.

2023-08-23 07:08 UTC, BernieWhite commented on tests/PSRule.Rules.Azure.Tests/Resources.ContainerApp.json
> +    "apiVersion": "2023-04-01-preview",
```suggestion
```

2023-08-23 19:03 UTC, BenjaminEngeset commented
@BernieWhite Looks great. I'm happy, all set!

Btw, the rule did work for me locally without the update in `RuleDataExportVisitor`, is that something that is used only for in-flight?

2023-08-24 00:51 UTC, BernieWhite approved these changes
Thanks @BenjaminEngeset. All good to merge.

2023-08-24 00:52 UTC, BernieWhite commented
> @BernieWhite Looks great. I'm happy, all set!
> 
> Btw, the rule did work for me locally without the update in `RuleDataExportVisitor`, is that something that is used only for in-flight?

When PSRule expands resources for pre-flight from code this should apply.

2023-08-24 02:30 UTC, merged