AML - initial set of AML rules and severity update
Azure/PSRule.Rules.Azure pull request #2500
Opened 2023-10-19 23:58 UTC by batemansogq

## PR Summary

the initial set of AML rules and severity update. 
This replaces an earlier pull request, which was extended. 

## PR Checklist

- [ ] PR has a meaningful title
- [ ] Summarized changes
- [ ] Change is not breaking
- [ ] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [ ] Unit tests created/ updated
  - [ ] Rule documentation created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2023-10-21 14:00 UTC, BernieWhite requested changes
@batemansogq I've migrated most of the changes over from the other PR.

Please double check and make sure you're ok with my updates.

2023-10-23 00:42 UTC, batemansogq commented on src/PSRule.Rules.Azure/rules/Azure.ML.Rule.yaml
> +    equals: Disabled
from the working sheet, these were intended as 2 separate rules; 

1. "Azure Machine Learning Workspaces should disable public network access" based upon https://portal.azure.com/#view/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2F438c38d2-3772-465a-a9cc-7a6666a275ce
2. "Disable public network access when behind vnet" - from https://github.com/Azure/azure-synapse-analytics-end2end/blob/main/Deploy/modules/AIServicesDeploy.bicep it also has a policy ref = https://portal.azure.com/#view/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2Fa10ee784-7409-4941-b091-663697637c0f

@nfmoore - can you please review and advise?

2023-10-23 01:26 UTC, nfmoore commented on src/PSRule.Rules.Azure/rules/Azure.ML.Rule.yaml
> +    equals: Disabled
According to the resource definition [here](https://learn.microsoft.com/en-us/azure/templates/microsoft.machinelearningservices/workspaces?pivots=deployment-language-bicep#workspaceproperties) the allowPublicAccessWhenBehindVnet and publicNetworkAccess properties are distinct with different functions. I think these should both remain.

2023-10-23 02:35 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.ML.Rule.yaml
> +    equals: Disabled
@nfmoore Ok got it. So we should ask a customer to configure both.

2023-10-23 02:42 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.ML.Rule.yaml
> +    equals: Disabled
Definitely this is going to be confusing for customers. For my own understanding what is the difference?

> There are two possible properties that you can configure:
>allow_public_access_when_behind_vnet - used by the Python SDK v1
>public_network_access - used by the CLI and Python SDK v2 Each property overrides the other. For example, setting >public_network_access will override any previous setting to allow_public_access_when_behind_vnet.
>Microsoft recommends using public_network_access to enable or disable public access to a workspace.

2023-10-24 23:46 UTC, nfmoore commented on src/PSRule.Rules.Azure/rules/Azure.ML.Rule.yaml
> +    equals: Disabled
@BernieWhite - you're right. with the v2 changes we should be using the public_network_access only.

2023-10-25 09:18 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.ML.Rule.yaml
> +    equals: Disabled
@nfmoore Ok thanks for confirming that.

2023-10-25 09:51 UTC, BernieWhite approved these changes
Thanks @batemansogq.

Double check my changes. But if you're ok with them, we're all good to merge.

Let me know.

2023-10-27 02:34 UTC, nfmoore commented
Looks good to me @BernieWhite. @batemansogq what are your thoughts ?

2023-10-30 20:22 UTC, batemansogq commented
@BernieWhite & @nfmoore - happy roll with the changes. I can rebaseline and start looking at the other rules.

2023-10-31 05:07 UTC, merged