Databricks - New Rules added
Azure/PSRule.Rules.Azure pull request #2643
Opened 2024-01-12 03:19 UTC by batemansogq

## PR Summary

- 2 ADB rules added, min SKU and Public Access
- 
- minor text update

## PR Checklist

- [ ] PR has a meaningful title
- [ ] Summarized changes
- [ ] Change is not breaking
- [ ] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [ ] Unit tests created/ updated
  - [ ] Rule documentation created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2024-01-12 07:42 UTC, BernieWhite requested changes
Thanks @batemansogq. Looks good. A few suggested changes below but otherwise all good.

2024-01-12 07:42 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.Databricks.Rule.yaml
> +        notEquals: trial
Don't have to change it. More just a call out that this is a simpler alternative:

```suggestion
  condition:
     field: sku.name
     notEquals: trial
```

2024-01-12 07:42 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.Databricks.Rule.yaml
> +        equals: Disabled
Don't have to change it. More just a call out that this is a simpler alternative:

```suggestion
  condition:
    field: properties.publicNetworkAccess
    equals: Disabled
```

Referencing a field with a specific value implies the property exists. PSRule first checks the property exists, then check that the value matches the expected value.

2024-01-12 07:42 UTC, BernieWhite commented on docs/en/rules/Azure.Databricks.PublicAccess.md
> +    }
Remove extra `}`.

```suggestion
```

2024-01-12 07:42 UTC, BernieWhite commented on docs/en/rules/Azure.Databricks.PublicAccess.md
> +- [Azure Databricks WorkspaceProperties](https://learn.microsoft.com/azure/templates/Microsoft.Databricks/workspaces?pivots=deployment-language-bicep#:~:text=WorkspaceCustomParameters-,publicNetworkA
Add WAF reference.

```suggestion
- [SE:06 Network controls](https://learn.microsoft.com/azure/well-architected/security/networking)
- [Azure Databricks WorkspaceProperties](https://learn.microsoft.com/azure/templates/Microsoft.Databricks/workspaces?pivots=deployment-language-bicep#:~:text=WorkspaceCustomParameters-,publicNetworkAccess,-The%20network%20access)
```

2024-01-12 07:42 UTC, BernieWhite commented on docs/en/rules/Azure.Databricks.PublicAccess.md
> +category: Application endpoints
New Well-Architected Framework v2 categories are aligned to the checklist.

```suggestion
category: SE:06 Network controls
```

2024-01-12 07:42 UTC, BernieWhite commented on docs/en/rules/Azure.Databricks.SKU.md
> +category: Scaling and Partitioning
[PE:03 Selecting services](https://learn.microsoft.com/azure/well-architected/performance-efficiency/select-services) might be a better fit for this one. But if you disagree, let me know.

```suggestion
category: PE:03 Selecting services
```

2024-01-12 07:42 UTC, BernieWhite commented on docs/en/rules/Azure.Databricks.SKU.md
> +- [Databricks Setup](https://learn.microsoft.com/azure/databricks/getting-started/#:~:text=Bicep-,Note,-When%20you%20create)
WAF link:

```suggestion
[PE:03 Selecting services](https://learn.microsoft.com/azure/well-architected/performance-efficiency/select-services)
- [Databricks Setup](https://learn.microsoft.com/azure/databricks/getting-started/#:~:text=Bicep-,Note,-When%20you%20create)
```

2024-01-12 07:42 UTC, BernieWhite commented on docs/en/rules/Azure.Databricks.SKU.md
> +Consider configuring Databricks workspaces to use either Standard or Premium tiers, dependant on the workload demands and NFRs.
```suggestion
Consider configuring Databricks workspaces to use either Standard or Premium tiers, dependant on the workload demands and non-functional requirements (NFRs).
```

2024-01-12 07:42 UTC, BernieWhite commented on docs/en/rules/Azure.Databricks.SKU.md
> +  },
Extra comma.

```suggestion
  }
```

2024-01-14 22:42 UTC, batemansogq commented
comments addressed, changes applied. Please review.

2024-01-16 02:23 UTC, BernieWhite approved these changes
Thanks @batemansogq. Changes look great. All good to merge.

2024-01-16 02:23 UTC, merged