feat: Updated Azure.APIM.AvailabilityZone
Azure/PSRule.Rules.Azure pull request #2874
Opened 2024-05-20 07:21 UTC by BenjaminEngeset

## PR Summary

Fixes #2788

Updated Azure.APIM.AvailabilityZone.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2024-05-20 07:24 UTC, BenjaminEngeset commented
Ready for review @BernieWhite. I would appreciate your feedback on it.

2024-05-20 14:46 UTC, BernieWhite requested changes
Thanks @BenjaminEngeset. Great work. Please see my suggestions below.

2024-05-20 14:46 UTC, BernieWhite commented on docs/CHANGELOG-v1.md
> +      [#2788](https://github.com/Azure/PSRule.Rules.Azure/issues/2788)
```suggestion
  - API Management:
    - **Important change**: Updated `Azure.APIM.AvailabilityZone` to improve accuracy with non-premium SKUs by @BenjaminEngeset.
      [#2788](https://github.com/Azure/PSRule.Rules.Azure/issues/2788)
      - Removed the `If` Premium SKU.
      - Added check for Premium SKU.
      - Updated tests.
      - Updated rule doc.
      - Bumped rule set to `2024_06`.
```

2024-05-20 14:46 UTC, BernieWhite commented on docs/en/rules/Azure.APIM.AvailabilityZone.md
> +For developer environments, supressing the rule might make sense as enabling zone redundancy for an API Management instance requries the `Premium` SKU currently.
The `NOTES` header is listed above. I like your positioning of `NOTES`, so maybe move the content from the `NOTES` above to this section so there is only one `NOTES`.

```suggestion
For developer environments, suppressing the rule might make sense as enabling zone redundancy for an API Management instance requries the `Premium` SKU currently.
```

2024-05-20 14:46 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1
> +Rule 'Azure.APIM.AvailabilityZone' -Ref 'AZR-000052' -Type 'Microsoft.ApiManagement/service' -Tag @{ release = 'GA'; ruleSet = '2021_12'; 'Azure.WAF/pillar' = 'Reliability'; } {
Let's bump the rule set as the behaviour has changed. You may need to update some baselines in baseline tests as a result.

```suggestion
Rule 'Azure.APIM.AvailabilityZone' -Ref 'AZR-000052' -Type 'Microsoft.ApiManagement/service' -Tag @{ release = 'GA'; ruleSet = '2024_06'; 'Azure.WAF/pillar' = 'Reliability'; } {
```

2024-05-20 14:46 UTC, BernieWhite commented on docs/en/rules/Azure.APIM.AvailabilityZone.md
> +Consider using availability zones for API Management instances.
```suggestion
Consider using at least two (2) scale units and availability zones to improve resiliency of API Management instances to zone failures.
```

2024-05-20 14:46 UTC, BernieWhite commented on docs/en/rules/Azure.APIM.AvailabilityZone.md
> +Enabling zone redundancy for an API Management instance in a additional region provides redundancy for *only* the gateway service component.
```suggestion
API Management supports using availability zones to provide zone redundency for key components.
Zone redundancy improves resiliency and high availability of the service by deploying scale units across data centers in physically separated zones.

The following are required to deploy a zone redundant configuration:

- API Management is deployed with the Premium SKU.
- At least two scale units must be deployed in separate availbility zones

Zone redundancy has a different configuration for the primary and additional regions:

- In the primary region, all service components are replicated across zones (gateway, management plane, and developer portal).
- In additional regions, *only* the gateway is replicated across zones.
  As the management plane/ developer portal service components are only deployed to the primary region.
```

2024-05-20 18:26 UTC, BenjaminEngeset commented
I think we should be all set, @BernieWhite. Please check the latest updates.

2024-05-21 02:37 UTC, BernieWhite approved these changes
Great work @BenjaminEngeset. All good to merge.

2024-05-21 02:37 UTC, merged