feat: Added Azure.VMSS.AvailabilityZone
Azure/PSRule.Rules.Azure pull request #2945
Opened 2024-06-17 18:36 UTC by BenjaminEngeset

## PR Summary

Fixes #2902

Azure.VMSS.AvailabilityZone.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2024-06-17 18:37 UTC, BenjaminEngeset commented
Ready for review @BernieWhite.

2024-06-18 13:14 UTC, BernieWhite requested changes
Great work @BenjaminEngeset. Please see the additional suggestions below.

2024-06-18 13:14 UTC, BernieWhite commented on docs/en/rules/Azure.VMSS.AvailabilityZone.md
> +See documentation references below for additional limitations and important information.
```suggestion
Virtual machine scale sets (VMSS) supports the use of availability zones to provide redundancy across physically separated zones.
When new instances are added to the VMSS as it scales, these instances are deployed across any zones that are configured.

For example:

- If the VMSS is configured to use only Zone 1, all new instances will be created in Zone 1.
- If the VMSS is configured to use three zones (Zone 1, Zone 2, and Zone 3), new instances will be distributed across these zones.

Also note:

- Using availability zones is suitable for stateless workloads.
- During scale-in operations, the number of instances in each zone may not be evenly distributed for all zones.

See documentation references below for additional limitations and important information.
```

2024-06-18 13:20 UTC, BenjaminEngeset commented
Hi @BernieWhite,

Thanks for the great feedback. I have adjusted accordingly now. Plesase check.

2024-06-18 13:37 UTC, BernieWhite approved these changes
Thanks @BenjaminEngeset. All good to merge.

2024-06-18 13:41 UTC, merged