Added Azure.VMSS.PublicIPAttached
Azure/PSRule.Rules.Azure pull request #3015
Opened 2024-08-12 10:59 UTC by BenjaminEngeset

## PR Summary

Fixes #3014

Added Azure.VMSS.PublicIPAttached.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2024-08-12 15:02 UTC, BernieWhite requested changes
Thanks @BenjaminEngeset. Looks great.

I have a few suggestions below.

2024-08-12 15:02 UTC, BernieWhite commented on tests/PSRule.Rules.Azure.Tests/Azure.VMSS.Tests.ps1
> +            $ruleResult.TargetName | Should -Be 'vmss-003', 'vmss-004', 'vmss-005', 'vmss-006/instance-B', 'nic-B';
As mentioned in rule.


```suggestion
            $ruleResult.Length | Should -Be 3;
            $ruleResult.TargetName | Should -BeIn 'vmss-003', 'vmss-006/instance-A', 'vmss-006/instance-B';
        }

        It 'Azure.VMSS.PublicIPAttached' {
            $filteredResult = $result | Where-Object { $_.RuleName -eq 'Azure.VMSS.PublicIPAttached' };

            # Fail
            $ruleResult = @($filteredResult | Where-Object { $_.Outcome -eq 'Fail' });
            $ruleResult.Length | Should -Be 3;
            $ruleResult.TargetName | Should -Be 'vmss-001', 'vmss-002', 'vmss-006/instance-A';

            $ruleResult[0].Reason | Should -BeExactly "The virtual machine scale set instances should not have public IP addresses directly attached to their network interfaces.";
            $ruleResult[1].Reason | Should -BeExactly "The virtual machine scale set instances should not have public IP addresses directly attached to their network interfaces.";
            $ruleResult[2].Reason | Should -BeExactly "The virtual machine scale set instances should not have public IP addresses directly attached to their network interfaces.";

            # Pass
            $ruleResult = @($filteredResult | Where-Object { $_.Outcome -eq 'Pass' });
            $ruleResult.Length | Should -Be 4;
            $ruleResult.TargetName | Should -Be 'vmss-003', 'vmss-004', 'vmss-005', 'vmss-006/instance-B';
```

2024-08-12 18:28 UTC, BenjaminEngeset commented
Requested changes have been implemented, @BernieWhite. Please check out my comment regarding your first suggestion.

I am happy with the rule now.

2024-08-14 03:16 UTC, BernieWhite approved these changes
Great work @BenjaminEngeset. All good to merge.

2024-08-14 03:16 UTC, merged

2024-08-14 06:52 UTC, BenjaminEngeset commented
Thanks @BernieWhite. Based on this screenshot, could you please elaborate on this? 

![image](https://github.com/user-attachments/assets/eff5e3da-e251-4e28-9c89-fc19414686c6)