Fixed Azure.AppService.AvailabilityZone only detects premium by tier
Azure/PSRule.Rules.Azure pull request #3036
Opened 2024-09-08 18:23 UTC by BenjaminEngeset

Fixes #3034

Fixed `Azure.AppService.AvailabilityZone` only detects premium by tier property.

## PR Summary

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [ ] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2024-09-08 18:27 UTC, BenjaminEngeset commented
Ready for review @BernieWhite.

We have discussed earlier that it would be nice to have the `AnyOf {}` exit when first condition is met so the reasoning doesn't end up like this, with duplicate. Behavior like the `-or` operator would be highly appreciated.

2024-09-09 18:49 UTC, BernieWhite requested changes
Thanks @BenjaminEngeset. Looks good. Thanks for having a look at this one.

Just a minor suggestion below.

2024-09-09 18:49 UTC, BernieWhite commented on src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1
> +    }
Let's add the paths here for additional detail.

```suggestion
    AnyOf {
        $Assert.In($TargetObject, 'sku.name', $sku.name).ReasonFrom(
            'sku.name',
            $LocalizedData.AppServiceAvailabilityZoneSKU,
            $TargetObject.name
        )
        $Assert.In($TargetObject, 'sku.tier', $sku.tier).ReasonFrom(
            'sku.tier',
            $LocalizedData.AppServiceAvailabilityZoneSKU,
            $TargetObject.name
        )
    }
```

2024-09-09 18:49 UTC, BernieWhite commented on tests/PSRule.Rules.Azure.Tests/Azure.AppService.Tests.ps1
>              );
```suggestion
            $ruleResult[0].Reason | Should -BeExactly @(
                "Path sku.name: The app service plan (plan-A) is not deployed with a SKU that supports zone-redundancy."
                "Path sku.tier: The app service plan (plan-A) is not deployed with a SKU that supports zone-redundancy."
                "Path properties.zoneRedundant: Does not exist."
            );
```

2024-09-09 20:02 UTC, BenjaminEngeset commented
Thanks for the great feedback @BernieWhite. I have adjusted accordingly now.

2024-09-12 23:39 UTC, BernieWhite approved these changes
Thanks @BenjaminEngeset. All good to merge.

2024-09-12 23:39 UTC, merged