Docs/adding first contrib
Azure/PSRule.Rules.Azure pull request #3188
Opened 2024-11-30 18:10 UTC by that-ar-guy

## PR Summary
fixes : #3097 
Added a new file `first-contributors-guide.md` in `docs/license-contributing/ ` for guiding new contributors so that they can easily onboard to the project and start contributing.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [ ] Change is not breaking
- [ ] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [ ] Unit tests created/ updated
  - [ ] Rule documentation created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

2024-12-02 16:41 UTC, BernieWhite requested changes
Thanks @that-ar-guy for your PR. Great start. I've added some suggestions. 

Also you can add a link to the table of contents here (https://github.com/Azure/PSRule.Rules.Azure/blob/3e2a3b708c53ebcd029a2b5cb5437a150de2119c/mkdocs.yml#L77) below index so that it will appear in the docs.

2024-12-02 16:41 UTC, BernieWhite commented on docs/license-contributing/first-contributors-guide.md
> +    - Ensure that you can build your changes locally. Follow the instructions in the [Building from Source](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/install.md#building-from-source)
```suggestion
    - Ensure that you can build your changes locally. Follow the instructions in the [Building from Source](https://azure.github.io/PSRule.Rules.Azure/install/#building-from-source) guide to set up your local environment for testing.
```

2024-12-02 16:41 UTC, BernieWhite commented on docs/license-contributing/first-contributors-guide.md
> +
I think we are provide an example of a unit test for a rule here. Example is: https://github.com/Azure/psrule.rules.azure/blob/main/tests/PSRule.Rules.Azure.Tests/Azure.ACR.Tests.ps1#L40-L56

2024-12-04 17:29 UTC, BernieWhite reviewed
Thanks for the updates @that-ar-guy. I've added some additional changes to your PR.

Have a look at let me know if you are happy with these changes.

2024-12-04 17:47 UTC, that-ar-guy commented
@microsoft-github-policy-service agree

2024-12-04 17:50 UTC, that-ar-guy commented
Thanks, @BernieWhite , for the updates! I've reviewed the additional changes, and they look great to me. I'm happy with these edits.

2024-12-04 18:41 UTC, merged